getting error
Error: ”Fatal Python error: could not acquire lock for
<_io.BufferedWriter name='<stdout>'> at interpreter shutdown, possibly
due to daemon threads”